### ISSUE TITLE
Looking forward to a strong adaptive attack

### ISSUE THREAD

**Issue by Crazygay12138** [xavihart/PDM-Pure#1]
From my perspective, this method is somewhat similar to DiffPure but only with a more powerful pixel-space diffusion model (DeepFloyd IF's super-resolution model). It is known that DiffPure can be bypassed by some strong adaptive attacks [1], which leaves us to doubt whether this method can also be bypassed. However, I did not see the authors discuss this issue since GLAZE and Mist depend on the VAE of LDM and use totally different surrogate models compared to the DeepFloyd IF. Thus, I kindly suggest the authors consider some powerful adaptive attacks instead of applying the PDM-Pure to attacks that do not take purification into account. I have done many experiments in this field and know that a simple JPEG has already done well [2] if no adaptive attack is conducted.

I am not sure what will happen, but if the authors prove that their PDM-Pure can not be bypassed, then PDM-Pure can close the cat-and-mouse game in the field of adversarial examples once and for all.

[1] Robust Evaluation of Diffusion-Based Adversarial Purification. ICCV2023
[2] JPEG Compressed Images Can Bypass Protections Against AI Editing

**Comment by xavihart** [comment]
Thanks for your interest, let me answer some of your questions:

> Simple JPEG already do well

JPEG can not do well, especially when the perturbations are colorful, e.g. AdvDM and Mist with eps=16. 

> DiffPure can be easily bypassed in [1], and PDM-Pure can also be attacked like this

This statement is not right. DiffPure can be bypassed [1] because it is used to do purification for a **classification task**! Our previous paper Diff-PGD also reflected this phenomenon,  in general, that the purification pipeline looks like (image -> PDM -> DNN-based classifier) can be easily attacked [a]; and for the image editing tasks it is not true (image -> PDM -> image), we try a lot of attacks and we find that PDM is quite robust. Details will be released in our paper, stay tuned!

The adaptive attacks as you mentioned have been exactly tried by this CVPR'24 paper [b] (Figure. 7), and they find that it does not work at all! Current evidence we have show that PDM may not be attackable, in the sense of generative quality, which means it is hard to add any perturbation to fool the PDM to generate chaotic results.


[a] Diffusion-Based Adversarial Sample Generation for Improved Stealthiness and Controllability


[b] Can Protective Perturbation Safeguard Personal Data from Being Exploited by Stable Diffusion?


Feel free to contact me for further discussion.

**Comment by Crazygay12138** [comment]
Thanks for your reply. I notice that you conduct AdvDM on pixel-space DM to attack PDM-Pure. In AdvDM, the protected image $x$ follows the SDEdit pipeline of the Stable Diffusion and serves as the noisy input at each timestep. However, I notice that, when the protected image is fed into DeepFloyd IF (stage II), it actually serves as a condition (with fixed noise level) concated with the noisy input at each timestep, and the noisy input is first sampled from torch.randn rather than the protected image with added noise, which is different from the pipeline of Stable Diffusion.

Have you tried to develop a new pipeline other than AdvDM to attack DeepFloyd IF? Since the pipeline of DeepFloyd IF is different from the SDEdit pipeline of Stable Diffusion, such a discrepancy might hinder AdvDM from cracking PDM-Pure.

**Comment by xavihart** [comment]
The protected image was input into Stage-II as x_t, not condition, please check how Stage-II works carefully. During the attack, we fix the condition (lower resolution of x) and only optimize the input.

**Comment by Crazygay12138** [comment]
I see. Thanks for your reply.
